location:
  lat: 
  long:

nextup:
  enabled: True
  apikey: 
  url:

whome:
  enabled: false
  server:

sleep:
  start: 00:00
  end: 06:00

sources:
  - name:
    apikey:
    url: 
    headers:

boxes:
  - label:
    type: 
    colour: 
    values:
      - path: 
        prefix:
        suffix:
        converter:
      - path:
        prefix:
        suffix:
        converter:
    centre:
      upper: 
      lower: 
