location:
  lat: 
  long:

sleep:
  start: 22:00
  end: 8:00

sources:
  - name:
    apikey:
    url: 

boxes:
  - label:
    type: 
    colour: 
    source: 
    values:
      - path: 
        prefix:
        suffix:
        converter:
      - path:
        prefix:
        suffix:
        converter:
    centre:
      upper: 
      lower: 
